### ISSUE TITLE
Error: Could not find file 'C:\Windows\system32\credentials.json'.

### ISSUE THREAD

**Issue by pelinski46** [abhinavminhas/Gmail-API-Helper#83]
When running a Blazor Hybrid application, I encounter the following error:
Error: Could not find file 'C:\Windows\system32\credentials.json'.
This issue occurs even though the same code works correctly when executed as a console application. The credentials.json file is properly placed in the project directory, and the Blazor Hybrid application is unable to locate it at runtime.

**Comment by abhinavminhas** [comment]
The error message indicates that the `credentials.json` file is expected at the path `C:\Windows\system32\credentials.json`, but it wasn't found.

To resolve this:

1. **Ensure the File is in the Correct Location:** Confirm that the `credentials.json` file is actually present in `C:\Windows\system32`. If not, you'll need to copy it there, though it's generally not recommended to store application-specific files in `C:\Windows\system32` as this folder is reserved for system files.

2. **Check File Permissions:** Even if the file is present, the application might not have the necessary permissions to read it. The `C:\Windows\system32` directory is highly restricted, so unless your application is running with elevated permissions (e.g., as an administrator), it may not be able to access files in this directory. You should check the permissions on the file and ensure the application has read access.

3. **Default Working Directory Considerations:**

- In a typical .NET console application, the default working directory is usually the directory from which the application is executed.
However, for Blazor Hybrid applications, the default working directory can vary depending on the platform and how the app is deployed. Blazor Hybrid apps do not run in the same environment as console applications, so the default working directory might differ across platforms (e.g., Windows, macOS, mobile).
- In general, a Blazor Hybrid app does not run in the same environment as a console application, so the default working directory is not as straightforward as it is for a console application.

4. **Alternative Solution:** If modifying the application's behavior is an option, you could implement your own version of [GetGmailService()](https://github.com/abhinavminhas/Gmail-API-Helper/blob/76aa8dccf0070a6b2b14dec16e4e0895e5068e24/GmailAPIHelper/GmailHelper.cs#L123) and specify a different path for the [credentials.json](https://github.com/abhinavminhas/Gmail-API-Helper/blob/76aa8dccf0070a6b2b14dec16e4e0895e5068e24/GmailAPIHelper/GmailHelper.cs#L134) file, preferably in a location that your application has guaranteed access to, such as a user-specific directory or an application-specific folder.

**Comment by pelinski46** [comment]
Yes, I chose the fourth option. I configured the path to the credentials.json file by adding the following line of code: 
`var credentialPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "credentials.json");` and it work
